# Generated by Django 3.1.4 on 2020-12-10 14:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=90),
        ),
    ]
