# Generated by Django 3.1.4 on 2021-01-05 20:28

import Tshala.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0003_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[Tshala.validators.file_size]),
        ),
    ]
