# Generated by Django 3.1.5 on 2021-01-25 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0004_auto_20210105_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='information',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
