# Generated by Django 3.1.5 on 2021-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0005_video_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('busstype', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=40)),
                ('regnumber', models.CharField(max_length=40)),
                ('nameofd', models.TextField(max_length=400)),
                ('nameofs', models.TextField(max_length=440)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='information',
        ),
    ]
