# Generated by Django 3.1.5 on 2021-01-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0006_auto_20210127_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tshala.add'),
        ),
    ]
