# Generated by Django 3.1.5 on 2021-01-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0008_auto_20210130_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='add',
            new_name='ad',
        ),
    ]
