# Generated by Django 3.1.5 on 2021-01-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tshala', '0009_auto_20210130_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ad',
        ),
        migrations.AddField(
            model_name='add',
            name='videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tshala.video'),
        ),
    ]
